In [3]:
import numpy as np
# a=[10,20,30]
# np.array(a)

array([10, 20, 30])

In [6]:
#Create a NumPy array with 6 elements. Print first, last element and shape.
a=[10,20,30,40,50,60]
print(a[0])
print(a[5])

10
60

In [8]:
# Create a 2D array (2x3). Print element at 2nd row 3rd column and first row.
b=[[1,2,3],[4,5,6],[7,8,9]]
np.ndim(b)

2

In [16]:
b[1:2]

[[4, 5, 6]]

In [22]:
#  Create array 1 to 10. Extract elements from index 3 to 7.
c=np.arange(1,11)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.ndim(c)
c[3:8]

array([4, 5, 6, 7, 8])

In [31]:
#  Replace negative values in an array with 0.
d=np.arange(1,7)
d

array([1, 2, 3, 4, 5, 6])

In [40]:
#  Find unique values and counts.
s=[[1,2,3],[3,4,5],[5,6,3]]
s

[[1, 2, 3], [3, 4, 5], [5, 6, 3]]

In [38]:
np.ndim(s)

2

In [41]:
import pandas as pd

In [43]:
s=pd.DataFrame(["name","Abin","Mark","Christopher"],["mark",80,85,95])
s

                0
mark         name
80           Abin
85           Mark
95    Christopher

In [46]:
u=pd.DataFrame(["A","B","C"])

In [47]:
u

   0
0  A
1  B
2  C